services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=bar
      - POSTGRES_USER=foo
      - POSTGRES_DB=exchange_rates
  redis:
    image: redis:latest
    ports:
      - 6379:6379
